theme: jekyll-theme-slate
title: Anthony’s Mac Labs and Personal Blog
url: https://maclabs.jazzace.ca
description: Anthony Reimer’s blog for Mac Admins and everyone following his personal journey
plugins:
  - jekyll-feed
author:
  name: Anthony Reimer
  mastodon: AnthonyReimer@mastodon.social